export enum constants {
  CONFIRM_CLOSED = '**MODAL_CLOSED**',
  MAC = 'mac',
  LINUX = 'linux',
  WINDOWS = 'windows',
  CONFIRM_CLOSED_AND_IGNORE_UPDATE = '**IGNORE_UPDATE_AND_MODAL_CLOSED**',
  CONFIRM_CLOSED_AND_DOWNLOAD_UPDATE = '**GO_TO_DOWNLOAD_PAGE_AND_MODAL_CLOSED**',
}
