name: Leapp Desktop App CD - prod

on:
  workflow_dispatch:

env:
  CERTIFICATE_APPLICATION_OSX_P12: ${{ secrets.CERTIFICATE_APPLICATION_OSX_P12 }}
  CERTIFICATE_OSX_P12: ${{ secrets.CERTIFICATE_OSX_P12 }}
  DECODE_PASSWORD: ${{ secrets.DECODE_PASSWORD }}
  DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  S3_BUCKET: s3://noovolari-leapp-website-distribution
  WIN_CERTIFICATE: ${{ secrets.WIN_CERTIFICATE }}
  WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
  ESIGNER_WIN_USERNAME: ${{ secrets.ESIGNER_WIN_USERNAME }}
  ESIGNER_WIN_PASSWORD: ${{ secrets.ESIGNER_WIN_PASSWORD }}
  ESIGNER_WIN_CREDENTIAL_ID: ${{ secrets.ESIGNER_WIN_CREDENTIAL_ID }}
  ESIGNER_WIN_TOTP: ${{ secrets.ESIGNER_WIN_TOTP }}
  ESIGNER_WIN_CLIENT_ID: ${{ secrets.ESIGNER_WIN_CLIENT_ID }}
  TEAM_REPOSITORY: ${{ secrets.TEAM_REPOSITORY }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - name: Prepare GIT
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        if: ${{ env.TEAM_REPOSITORY != '' }}
        with:
          repository: ${{ env.TEAM_REPOSITORY }}
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: leapp-team
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Inject Team Feature
        if: ${{ env.TEAM_REPOSITORY != '' }}
        run: |
          cd packages/core
          npm install
          npm run build
          cd ../..
          mv leapp-team ..
          cd ../leapp-team/packages/leapp-team-core
          npm run bootstrap
          cd ../leapp-team-service
          npm install
          npm run test
          npm run enable-team-features-prod

      - name: Build Win desktop app
        shell: bash
        run: |
          cd packages/desktop-app
          curl https://asset.noovolari.com/signing-tool/CodeSignTool-v1.2.7-windows.zip --output CodeSignTool-v1.2.7-windows.zip -s
          unzip CodeSignTool-v1.2.7-windows.zip
          CONFIG_FILE=code_sign_tool.properties
          cat "./CodeSignTool-v1.2.7-windows/conf/$CONFIG_FILE"
          npm install
          npm run release-win
          rm -Rf ./release/win-unpacked
          rm -Rf ./release/.cache
          rm -Rf ./release/builder-debug.yml
          rm -Rf ./release/builder-effective-config.yaml
          TAG_VERSION=0.24.5
          rm "./release/Leapp-${TAG_VERSION}-win.zip" ||:
          powershell "Compress-Archive './release/Leapp Setup ${TAG_VERSION}.exe' './release/Leapp-${TAG_VERSION}-win.zip'"
          powershell "Compress-Archive './release/Leapp Setup ${TAG_VERSION}.exe' './release/Leapp-windows.zip'"
          powershell "Compress-Archive './release/' './release/Leapp-windows-release.zip'"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Leapp-windows-release.zip
          path: packages/desktop-app/release/Leapp-windows-release.zip
