on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-cask to update this formula:
          formula-name: leapp
          formula-path: Casks/leapp.rb
          homebrew-tap: Homebrew/homebrew-cask
        env:
          COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
